image: kirschbaumdevelopment/laravel-test-runner:8.3

services:
  - name: mysql:8.0
    alias: mysql

variables:
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: laravel_db
  DB_USERNAME: root
  DB_PASSWORD: password123
  MYSQL_ROOT_PASSWORD: password123
  MYSQL_DATABASE: laravel_db

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/

build_job:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --ignore-platform-reqs
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    expire_in: 1h
    paths:
      - vendor/
      - .env

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - php artisan migrate --force
    - php artisan test

deploy_production:
  stage: deploy
  dependencies:
    - build_job
  script:
    - echo "Depsloying to Nginx folder..."
    # 1. Pindahkan file tapi amankan .env asli laptop
    - rsync -av --exclude='.env' --exclude='storage/database.sqlite' . /var/www/laravel-live/
    
    # 2. Masuk ke folder live
    - cd /var/www/laravel-live
    
    # 3. Jalankan perintah tanpa memicu koneksi database yang berat
    - composer install --no-dev --optimize-autoloader --ignore-platform-reqs
    
    # 4. Clear cache agar Laravel baca .env (127.0.0.1) milik laptop
    - php artisan config:clear
    - php artisan cache:clear
    
    # 5. Jalankan migrasi (Opsional jika ingin otomatis)
    # Catatan: Ini akan menggunakan database MySQL asli di laptop kamu
    - php artisan migrate --force
    
    # 6. Set permission folder
    - chmod -R 775 storage bootstrap/cache
  when: manual
  only:
    - main
