# Ubah dari 8.2 ke 8.3
image: kirschbaumdevelopment/laravel-test-runner:8.3

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/

build_job:
  stage: build
  script:
    # Kita tambahkan flag --ignore-platform-reqs untuk berjaga-jaga jika ada mismatch kecil
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --ignore-platform-reqs
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    expire_in: 1h
    paths:
      - vendor/
      - .env

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - php artisan test

deploy_production:
  stage: deploy
  script:
    - echo "Deploying to Nginx folder..."
    - cp -R . /var/www/laravel-live
    - cd /var/www/laravel-live
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - chmod -R 775 storage bootstrap/cache
    - chown -R $USER:www-data storage bootstrap/cache
  when: manual # Ganti jadi 'always' kalau mau otomatis tanpa klik
  only:
    - main
