name: Deploy Laravel via Rsync

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files with Rsync
        run: |
          rsync -av --no-perms --exclude='.env' --exclude='.git' . /var/www/laravel-live/

      - name: Post-Deployment Commands
        run: |
          cd /var/www/laravel-live
          
          # Hapus file cache view supaya tidak bentrok ownership
          rm -rf storage/framework/views/*.php
          
          composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts
          php artisan migrate --force || echo "Nothing to migrate"
          php artisan config:clear
          php artisan cache:clear
          
          # Cukup jalankan chmod saja, tidak usah chgrp/chown di sini
          chmod -R 775 storage bootstrap/cache
