name: Deploy Laravel via Rsync

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files with Rsync
        run: |
          rsync -av --no-perms --exclude='.env' --exclude='.git' . /var/www/laravel-live/

      - name: Post-Deployment Commands
        run: |
          cd /var/www/laravel-live
          composer install --no-dev --optimize-autoloader --ignore-platform-reqs
          php artisan migrate --force || echo "Migration skipped"
          php artisan config:clear
          php artisan cache:clear
          # Hapus sudo di bawah ini agar tidak minta password
          chmod -R 775 storage bootstrap/cache
